# Generated by Django 5.2.5 on 2025-09-04 08:25

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.PositiveBigIntegerField(help_text='Enter 6-digit pin code', validators=[userauths.models.validate_pin_length]),
        ),
    ]
